[package]
name = "yang-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
miette = { version = "7.2.0", features = ["fancy"] }
phf = { version = "0.11.2", features = ["macros"] }
regex = "1.10.6"